# Generated by Django 5.1.1 on 2024-09-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(choices=[('TOYOTA', 'toyota'), ('HONDA', 'honda'), ('FORD', 'ford'), ('LEXUS', 'lexus'), ('CHEVROLET', 'chevrolet'), ('BMW', 'bmw'), ('MERCEDES-BENZ', 'mercedes-benz'), ('MAZDA', 'mazda'), ('AUDI', 'audi'), ('KIA', 'kia'), ('HYUNDIA', 'hyundia'), ('NISSAN', 'nissan'), ('VOLKSWAGEN', 'volkswagen')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('engine', models.DecimalField(decimal_places=1, max_digits=10)),
                ('rhd_lhd', models.CharField(choices=[('LHD', 'Left-Hand drive'), ('RHD', 'Right-Hand drive')], max_length=3)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='car_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
