# Generated by Django 5.1.1 on 2024-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('TOYOTA', 'Toyota'), ('HONDA', 'Honda'), ('FORD', 'Ford'), ('LEXUS', 'Lexus'), ('CHEVROLET', 'Chevrolet'), ('BMW', 'Bmw'), ('MERCEDES-BENZ', 'Mercedes-benz'), ('MAZDA', 'Mazda'), ('AUDI', 'Audi'), ('KIA', 'Kia'), ('HYUNDAI', 'Hyundai'), ('NISSAN', 'Nissan'), ('VOLKSWAGEN', 'Volkswagen')], max_length=50),
        ),
    ]
